### ISSUE TITLE
Handle layers with more than 5 dimensions

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari-metadata#41]
When using a 6D image, we run into an error as in the following screenshot.

![image](https://user-images.githubusercontent.com/2608297/225770898-8689d2f3-16a0-4fde-9f9a-30b2e1a1aecf.png)

We may also want to handle >5D layers when it comes to writing, since the current version of ome-zarr does not support that.

**Comment by andy-sweet** [comment]
@chili-chiu : do you have any more context on this bug? E.g. do you remember what action you took to create the bug?

I tried adding a 6D image from scratch or in addition to a 3D image, and could not cause the bug.

It's also possible that I fixed this with other changes since you tested.

**Comment by chili-chiu** [comment]
I installed the latest version this morning and can no longer reproduce this bug. Looks like it's fixed :)
